### ISSUE TITLE
"TypeError: audioContext.audioWorklet is undefined" error when joining a room over port 8000

### ISSUE THREAD

**Issue by ericfont** [jacktrip-webrtc/jacktrip-webrtc#10]
I'm on develop-datachannel latest commit (as of two months ago: https://github.com/jacktrip-webrtc/jacktrip-webrtc/commit/1bc879536529eff0bb778d519de20b05459ed4ba)

Seems to work fine on firefox & chrome on my linux machines (Arch Linux & Debian 10), but I'm having the following problem running the client on Windows 10 x86-64 (both my windows 10 machine and someone else's) upon creating a room:

Firefox 80.0.1:
![jacktrip-webrtc_firefox80-0-1](https://user-images.githubusercontent.com/6502474/93836746-b3f5c380-fc51-11ea-9939-63e0f44a219d.PNG)

Chrome 85.0.4183.121:
![jacktrip-webrtc error](https://user-images.githubusercontent.com/6502474/93836776-ca9c1a80-fc51-11ea-8bc2-73f3b402e4fd.PNG)

That first warning in Chrome "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page" leads me to https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio which seems to indicate the error might be due to AudioWorklet not being allowed to be created prior to user input due to some policy against autoplay abuse.

**Comment by ericfont** [comment]
Similar error on Windows 10 when trying to join a room.

Firefox:
![image](https://user-images.githubusercontent.com/6502474/93837430-10f27900-fc54-11ea-9991-aa46de16fb8e.png)

Chrome:
![image](https://user-images.githubusercontent.com/6502474/93837484-3a130980-fc54-11ea-8830-2483a154740f.png)

**Comment by ericfont** [comment]
I don't see any unusual messages in the nodejs server terminal, so this seems to be a client-only issue.

**Comment by ericfont** [comment]
I've managed to get the same error on Debian Chromium (83.0.4103.116 Debian 10.5 64-bit): ![image](https://user-images.githubusercontent.com/6502474/93838602-3bdecc00-fc58-11ea-9549-db3437f0a741.png)

I recall last night I was doing some tests with some virtual pulseaudio sinks/sources on this Debian machine, so I may have confused my browser into using a no-longer-existing audio device now.

**Comment by ericfont** [comment]
Changed the title, because it seems this error happens in both Linux & Windows for both browsers too.  It seems the error happens when creating or joining a room when not on localhost of the server machine.  Or even when joining a room on another browser on localhost.  So it seems the only.

Somehow I remember a few days ago being able to successfully join a room...so I'm a bit confused.

**Comment by ericfont** [comment]
I updated the title again...because it seems this issue only happens when using port 8000, while port 44300 works ok.

**Comment by ericfont** [comment]
So now my theory is that the browsers don't allow creating an audio context to an unsecure connection, hence why they allow localhost:8000 but don't allow creating an audio context over port 8000 when the url is not localhost.

**Comment by ericfont** [comment]
I guess the README.md is consistent with this limitation when it says:

> "Now you can connect to http://localhost:8000 or https://localhost:44300 and to https://<host-ip-address>:44300 if connecting from another device."

Though it would be nice if this were more clear by saying that cannot access remotely over http on port 8000, and if trying to do so results in a clear error message telling the remote user to use https over port 44300.

**Comment by ericfont** [comment]
would be nice if the [Room link] share popup when creating a room from localhost:8000 needs to not provide a :8000 link that isn't going to work, or at least warn the user about this limitation if it does provide a :8000 link.

**Comment by matteosacchetto** [comment]
Hi @ericfont,
you are sort of right. The audioContext can be created also when using an unsecure connection, but audioWorklets can not. When you try to connect to the http server, instead of the https server, from a remote machine, in the AudioContext object you will not have the audioWorklet properties, since it requires a secure context, and so you cannot use audioWorklets, which are the foundation of this project.

You are right, we could clarify it better in the README.md

I guess browsers allow audioWorklets to work on localhost as well for development reasons, since when connecting to localhost the context is "sort of secure".

**Comment by ericfont** [comment]
Thanks.  I've actually in the meantime figured out how to setup a HTTPS certificate from Let's Encrypt, so people outside my LAN can access via a domain name...

Though a note for anyone reading, if you want to setup a https SSL certificate, [there is an additional step after setting your .env file to have NODE_ENV=production and SSL_CERT_PATH and SSL_KEY_PATH correctly pointing to your certificate & key](https://stackoverflow.com/questions/48078083/lets-encrypt-ssl-couldnt-start-by-error-eacces-permission-denied-open-et): You must allow your nodejs server to be able to access the cert and key with the node user's permission.

**Comment by matteosacchetto** [comment]
Hi @ericfont,
i've updated the README.md file making more clear that you need to use https if you are connecting from a different device.
