### ISSUE TITLE
OpenSSL location on macOS

### ISSUE THREAD

**Issue by noahhorn** [jacktrip-webrtc/jacktrip-webrtc#2]
Hello,
I think macOS stores OpenSSL in a different location than Linux. I installed mine through Homebrew and it put it into: /usr/local/opt/openssl
Perhaps add a check for that folder as well? The secure server does not currently load for me. See attached screenshot. Thank you!

<img width="1539" alt="OpenSSL not found" src="https://user-images.githubusercontent.com/65310237/88317773-c30ad480-cce7-11ea-8332-2d900d22811c.png">

**Comment by matteosacchetto** [comment]
Hello,  
Sure, I can add a check for that path as well.  
In the meantime, if you want to specify a different path to OpenSSL w.r.t. the "default" one, you can do it through a .env file. You just need to create a .env file int the root folder of the project and you need to add these lines to that file:
```
# Defining path to openSSL
PATH_OPENSSL=/usr/local/opt/openssl
```

More details about the .env file and the variables that can be defined can be found [here](https://github.com/jacktrip-webrtc/jacktrip-webrtc/blob/develop-datachannel/documentation/Configuration.md)

**Comment by matteosacchetto** [comment]
Hi Noah, now it should automatically find OpenSSL in the system.  
Check if it works now and let me know

**Comment by noahhorn** [comment]
Excellent — it found it perfectly! Thank you!
