### ISSUE TITLE
.env file sample

### ISSUE THREAD

**Issue by omarcostahamido** [jacktrip-webrtc/jacktrip-webrtc#4]
Create a sample .env file or maybe even just include a code box [here](https://github.com/jacktrip-webrtc/jacktrip-webrtc/blob/develop-datachannel/documentation/Configuration.md) with a sample of what the .env file will look like.

Also, if HTTP defaults to true, and HTTPS defaults to true, which one is it using by default?

O

**Comment by omarcostahamido** [comment]
in a way, this refers to #2

**Comment by matteosacchetto** [comment]
Hi, there is already a file in the repository with this purpose.  
Take a look at the [env.example](https://github.com/jacktrip-webrtc/jacktrip-webrtc/blob/develop-datachannel/.env.example) file in the root folder of the project

**Comment by matteosacchetto** [comment]
As for your second question, both HTTP and HTTPS servers are started and available to be used, there is not a default, since both share the same information. It is up to the user which hosts the server to decide which one to use, and if one of them is not necessary than it is his responsibility to turn it off

**Comment by matteosacchetto** [comment]
I will keep both the codebox example and add a reference to the .env.example

**Comment by omarcostahamido** [comment]
> Hi, there is already a file in the repository with this purpose.
> Take a look at the [env.example](https://github.com/jacktrip-webrtc/jacktrip-webrtc/blob/develop-datachannel/.env.example) file in the root folder of the project

_ooof!_ I didn't see that.


> I will keep both the codebox example and add a reference to the .env.example

sounds good.
