### ISSUE TITLE
STATIC_PATH instead of STATIC

### ISSUE THREAD

**Issue by omarcostahamido** [jacktrip-webrtc/jacktrip-webrtc#5]
Change "STATIC" to "STATIC_PATH" [here](https://github.com/jacktrip-webrtc/jacktrip-webrtc/blob/develop-datachannel/documentation/Configuration.md) (and everywhere else it needs to be changed).

O

**Comment by matteosacchetto** [comment]
Sure, I will do it as soon as possible

**Comment by omarcostahamido** [comment]
:)
