### ISSUE TITLE
OPENSSL_PATH instead of PATH_OPENSSL

### ISSUE THREAD

**Issue by omarcostahamido** [jacktrip-webrtc/jacktrip-webrtc#6]
For the sake of consistency, change "PATH_OPENSSL" to "OPENSSL_PATH" [here](https://github.com/jacktrip-webrtc/jacktrip-webrtc/blob/develop-datachannel/documentation/Configuration.md) (and everywhere it needs to be changed).

O

**Comment by matteosacchetto** [comment]
You are right, consistency is key. As for #5 I will do it as soon as possible

**Comment by omarcostahamido** [comment]
nice
